# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 14:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanWar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('F', 'Future')], max_length=1)),
                ('war_type', models.CharField(choices=[('XP', 'Experience'), ('RES', 'Resources'), ('DMG', 'Damage'), ('GL', 'Glory')], max_length=3)),
                ('result', models.CharField(choices=[('w', 'won'), ('l', 'lost')], max_length=1)),
                ('enemyClans', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.PositiveSmallIntegerField()),
                ('stars', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(choices=[('M', 'Member'), ('O', 'Officer'), ('C', 'Co_leader'), ('L', 'Leader')], max_length=1)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TerittoryBattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('F', 'Future')], max_length=1)),
                ('planet', models.CharField(max_length=20)),
                ('terittory', models.CharField(max_length=50)),
                ('assignedUsers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Hypothesis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='teammate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
