# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanwar',
            name='result',
            field=models.CharField(choices=[('w', 'won'), ('l', 'lost'), ('p', 'proccesing')], max_length=1),
        ),
    ]
