# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20160629_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(default=0, height_field='100', upload_to='', width_field='100'),
            preserve_default=False,
        ),
    ]
