# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_auto_20160702_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clanwar',
            old_name='enemyClans',
            new_name='enemy_clans',
        ),
    ]
