# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_auto_20160702_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terittorybattle',
            old_name='assignedUsers',
            new_name='assigned_users',
        ),
    ]
