# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_auto_20160702_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypothesis',
            name='stars',
            field=models.CharField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3)], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='hypothesis',
            unique_together=set([('opponent', 'stars')]),
        ),
    ]
