# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_auto_20160703_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terittorybattle',
            name='hypothesis',
        ),
        migrations.AddField(
            model_name='terittorybattle',
            name='hypothesis',
            field=models.ManyToManyField(blank=True, default=0, null=True, to='basic.Hypothesis'),
        ),
    ]
