# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_auto_20160703_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terittorybattle',
            name='hypothesis',
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='terittory_battle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='basic.TerittoryBattle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rules',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hypothesis',
            unique_together=set([('terittory_battle', 'opponent', 'stars')]),
        ),
    ]
