# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0016_auto_20160703_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
