# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0017_auto_20160705_2013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClanWar',
        ),
        migrations.AlterUniqueTogether(
            name='hypothesis',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='hypothesis',
            name='teammate',
        ),
        migrations.RemoveField(
            model_name='hypothesis',
            name='terittory_battle',
        ),
        migrations.RemoveField(
            model_name='terittorybattle',
            name='assigned_users',
        ),
        migrations.DeleteModel(
            name='Hypothesis',
        ),
        migrations.DeleteModel(
            name='TerittoryBattle',
        ),
    ]
