# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0018_auto_20160707_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rules',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.Member'),
        ),
    ]
