# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 21:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanWar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('F', 'Future')], max_length=1)),
                ('war_type', models.CharField(choices=[('XP', 'Experience'), ('RES', 'Resources'), ('DMG', 'Damage'), ('GL', 'Glory')], max_length=3)),
                ('result', models.CharField(choices=[('w', 'won'), ('l', 'lost'), ('p', 'proccesing')], max_length=1)),
                ('enemy_clans', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.PositiveSmallIntegerField()),
                ('stars', models.CharField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3)], max_length=1)),
                ('teammate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.CharField(choices=[('S', 'Syra'), ('T', 'Terra')], max_length=1)),
                ('name', models.CharField(max_length=50)),
                ('time_for_preparation', models.DateTimeField(blank=True, null=True)),
                ('time_for_battle', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TerritoryBattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('F', 'Future')], max_length=1)),
                ('assigned_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battles.Territory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='terittory_battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.TerritoryBattle'),
        ),
        migrations.AlterUniqueTogether(
            name='hypothesis',
            unique_together=set([('terittory_battle', 'opponent', 'stars')]),
        ),
    ]
