# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypothesis',
            name='teammate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Member'),
        ),
        migrations.AlterField(
            model_name='territorybattle',
            name='assigned_users',
            field=models.ManyToManyField(to='basic.Member'),
        ),
    ]
