# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_auto_20160709_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='time_for_battle',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='territory',
            name='time_for_preparation',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
